### ISSUE TITLE
What do you think about the new API for version 2.0.0

### ISSUE THREAD

**Issue by morajabi** [morajabi/styled-media-query#8]
<img width="408" alt="screen shot 2017-08-24 at 11 49 34 am" src="https://user-images.githubusercontent.com/12202757/29654426-6ce77886-88c2-11e7-8d5d-562fcabc959a.png">

I'm working on a new API in version 2 and so far I came to this. What do you think about it? Is it readable? What can we add or change?

Note: The old API (`media.to.large`) is still there and you'll have no problems using it, but probably in version 3 it will be removed.

**Comment by tylerreckart** [comment]
@morajabi I love this API 😄 Making the definitions as verbose as possible will make it much easier for junior devs to get up and running with this. I remember defining media queries as being a pain point when I started out

**Comment by morajabi** [comment]
@tylerreckart Finally, It is released now and you can use it!
